name: ciland
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  bloc: ^9.0.0
  provider: ^6.1.2
  flutter_svg: ^2.0.17
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  firebase_core: ^3.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
