// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALqAn_F64nsJzuZwCiI726DOxvhGTSeTs',
    appId: '1:611420800370:web:69b0bc253e82d332b049eb',
    messagingSenderId: '611420800370',
    projectId: 'ciland',
    authDomain: 'ciland.firebaseapp.com',
    storageBucket: 'ciland.firebasestorage.app',
    measurementId: 'G-D3LXSS1W3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn4alcXQG2LkMuJWM-PytAU0CLR8tYbAc',
    appId: '1:611420800370:android:7cfdbc3071c3f20eb049eb',
    messagingSenderId: '611420800370',
    projectId: 'ciland',
    storageBucket: 'ciland.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByPYopl6TUO7Q2FzZWS9jv-2H7ATvEEwE',
    appId: '1:611420800370:ios:f241730e7531a2e1b049eb',
    messagingSenderId: '611420800370',
    projectId: 'ciland',
    storageBucket: 'ciland.firebasestorage.app',
    iosBundleId: 'com.example.ciland',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByPYopl6TUO7Q2FzZWS9jv-2H7ATvEEwE',
    appId: '1:611420800370:ios:f241730e7531a2e1b049eb',
    messagingSenderId: '611420800370',
    projectId: 'ciland',
    storageBucket: 'ciland.firebasestorage.app',
    iosBundleId: 'com.example.ciland',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALqAn_F64nsJzuZwCiI726DOxvhGTSeTs',
    appId: '1:611420800370:web:bdd9fc5f83cd8219b049eb',
    messagingSenderId: '611420800370',
    projectId: 'ciland',
    authDomain: 'ciland.firebaseapp.com',
    storageBucket: 'ciland.firebasestorage.app',
    measurementId: 'G-6MEBTELZ1H',
  );
}
